// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBga7mqvosRX5JOZAtynq8lNebQD1bDemw',
    appId: '1:613832828806:web:350987b8bca1efb9d86e07',
    messagingSenderId: '613832828806',
    projectId: 'blueprintbloc',
    authDomain: 'blueprintbloc.firebaseapp.com',
    storageBucket: 'blueprintbloc.firebasestorage.app',
    measurementId: 'G-EPZDCP9FRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANPP9Dj5sTnfsgmQmmVSSFYRZupGiWzzI',
    appId: '1:613832828806:android:493541ed26cd9756d86e07',
    messagingSenderId: '613832828806',
    projectId: 'blueprintbloc',
    storageBucket: 'blueprintbloc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCanas7LLvjEFfPVi2dOAed09HooNNYz9I',
    appId: '1:613832828806:ios:6f06bc47e1a9338bd86e07',
    messagingSenderId: '613832828806',
    projectId: 'blueprintbloc',
    storageBucket: 'blueprintbloc.firebasestorage.app',
    iosBundleId: 'com.example.blueprintBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCanas7LLvjEFfPVi2dOAed09HooNNYz9I',
    appId: '1:613832828806:ios:6f06bc47e1a9338bd86e07',
    messagingSenderId: '613832828806',
    projectId: 'blueprintbloc',
    storageBucket: 'blueprintbloc.firebasestorage.app',
    iosBundleId: 'com.example.blueprintBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBga7mqvosRX5JOZAtynq8lNebQD1bDemw',
    appId: '1:613832828806:web:6dfc0a9729896e65d86e07',
    messagingSenderId: '613832828806',
    projectId: 'blueprintbloc',
    authDomain: 'blueprintbloc.firebaseapp.com',
    storageBucket: 'blueprintbloc.firebasestorage.app',
    measurementId: 'G-SD0RLP0EE1',
  );
}
